wallpaper {
	monitor = 
	# path = ~/.config/hypr/.wallpaper/aaa.png
	# path = ~/.config/hypr/.wallpaper/wall2.png
	# path = ~/.config/hypr/.wallpaper/nature4.jpg
	path = ~/.config/hypr/.wallpaper/ducks.jpg
}
splash = false
