import = [
  "~/.config/alacritty/catppuccin-macchiato.toml"
]

[env]
TERM="xterm-256color"

[font]
size = 17

[font.normal]
family="JetBrainsMono Nerd Font"
style="Regular"

[font.bold]
family="jetbrainsmono nerd font"
style="Bold"

[font.italic]
family="jetbrainsmono nerd font"
style="Italic"

[font.bold_italic]
family="jetbrainsmono nerd font"
style="Bold Italic"


[window]
decorations = "none"
